;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GameplayCue.Damaged",NewTagName="GameplayCue.OnDamage")
+GameplayTagList=(Tag="GameplayCue.OnDamage",DevComment="")
+GameplayTagList=(Tag="Spell.Contagion",DevComment="")
+GameplayTagList=(Tag="Spell.Digitize",DevComment="")
+GameplayTagList=(Tag="Spell.FleshWall",DevComment="")
+GameplayTagList=(Tag="Spell.Lockjaw",DevComment="")
+GameplayTagList=(Tag="Spell.VoltCascade",DevComment="")
+GameplayTagList=(Tag="State.PlacingWall",DevComment="")
+GameplayTagList=(Tag="Status.OnDamage",DevComment="")

